homelab:
  name: Homelab
  subtitle: EuskadiTech
  icon: "fas fa-home"

warning:
  enabled: true
  title: "Fallo solucionado"
  content: "El router Vodafone ya esta completamente operativo."

reverse_proxy:
  - domain_name: hl.tech.eus
    scheme: http
    host: 100.75.123.40 # Margaret Tailscale
    port: 8080
  - domain_name: dav.tech.eus
    scheme: http
    host: 100.75.123.40 # Margaret Tailscale
    port: 8809
  - domain_name: cctv.ei.tech.eus
    scheme: http
    host: 100.75.123.40 # Margaret Tailscale
    port: 8765
  - domain_name: tech.eus
    scheme: http
    host: 100.75.123.40 # Margaret Tailscale
    port: 8080
  - domain_name: ffplayout.ei.tech.eus
    scheme: http
    host: 100.75.123.40 # Margaret Tailscale
    port: 8787
  - domain_name: homeassistant.ei.tech.eus
    scheme: http
    host: 100.75.123.40 # Margaret Tailscale
    port: 8123
  - domain_name: cups.ei.tech.eus
    scheme: http
    host: 100.75.123.40 # Margaret Tailscale
    port: 631
  - domain_name: pihole.ei.tech.eus
    scheme: http
    host: 100.75.123.40 # Margaret Tailscale
    port: 8081
  - domain_name: getaldea.axau.tech.eus
    scheme: http
    host: 100.75.123.40 # Margaret Tailscale
    port: 12321
  - domain_name: translator.axau.tech.eus
    scheme: http
    host: 100.75.123.40 # Margaret Tailscale
    port: 12320
  - domain_name: aula.tech.eus
    scheme: http
    host: 100.75.123.40 # Margaret Tailscale
    port: 15000
  - domain_name: nextcloud.ei.tech.eus
    scheme: http
    host: 100.75.123.40 # Margaret Tailscale
    port: 8082
  - domain_name: paperless.ei.tech.eus
    scheme: http
    host: 100.75.123.40 # Margaret Tailscale
    port: 2226
  - domain_name: axel.tech.eus
    scheme: http
    host: 100.75.123.40 # Margaret Tailscale
    port: 8811
  - domain_name: ba.tech.eus
    scheme: http
    host: 100.75.123.40 # Work01 Tailscale
    port: 14000
  - domain_name: bb.tech.eus
    scheme: http
    host: 100.75.123.40 # Work01 Tailscale
    port: 14001
  - domain_name: docs.tech.eus
    scheme: http
    host: 100.115.231.1 # Huevo23 Tailscale
    port: 82
  - domain_name: nodered.ei.tech.eus
    scheme: http
    host: 100.115.231.1 # Huevo23 Tailscale
    port: 1880
  - domain_name: nginxproxymanager.ei.tech.eus
    scheme: http
    host: 127.0.0.1 # Localhost (Nginx Proxy Manager)
    port: 81
dashboard:
  - name: "Automatización"
    icon: "fas fa-home"
    items:
      - name: "Home Assistant"
        url: "https://homeassistant.ei.tech.eus/"
        target: "_blank"
      - name: "Node-RED (Dashboard)"
        url: "https://nodered.ei.tech.eus/dashboard/tablet-cocina"
        target: "_blank"
  - name: "Datos"
    icon: "fas fa-home"
    items:
      - name: "Nextcloud"
        url: "https://nextcloud.ei.tech.eus/"
        target: "_blank"
      - name: "Rei3 Alpha"
        url: "https://ba.tech.eus/"
      - name: "Rei3 Beta"
        url: "https://bb.tech.eus/"
        target: "_blank"
  - name: "Ciberseguridad"
    icon: "fas fa-home"
    items:
      - name: "Covenant Admin"
        url: "https://covenant.ei.tech.eus/"
        target: "_blank"
      - name: "Covenant 1"
        url: "https://ca.tech.eus/"
      - name: "Covenant 2"
        url: "https://cb.tech.eus/"
        target: "_blank"
      - name: "Covenant 3"
        url: "https://cc.tech.eus/"
        target: "_blank"
      - name: "Covenant 4"
        url: "https://cd.tech.eus/"
        target: "_blank"
  - name: TV
    icon: fas fa-wifi
    items:
      - name: ffPlayout
        url: https://ffplayout.ei.tech.eus/
        target: "_blank"
  - name: "Red"
    icon: "fas fa-wifi"
    items:
      - name: "Nginx Proxy Manager"
        url: "https://nginxproxymanager.ei.tech.eus/"
        target: "_blank"
      - name: "Pi-Hole"
        url: "https://pihole.ei.tech.eus/"
        target: "_blank"
      - name: "Router Vodafone"
        url: "http://192.168.0.1"
        target: "_blank"
      - name: "Repetidor TP-Link"
        url: "http://192.168.0.2"
        target: "_blank"
  - name: "Infraestructura"
    icon: "fas fa-server"
    items:
      - name: "Homelab Repo"
        url: "https://github.com/naielv/homelab"
        target: "_blank"
      - name: "Impresoras"
        url: "https://cups.ei.tech.eus/"
        target: "_blank"
      - name: "Generar Contraseña"
        url: "https://www.useapassphrase.com/"
        target: "_blank"
      - name: "Cloudflare"
        url: "https://dash.cloudflare.com/"
        target: "_blank"
      - name: "Documentación"
        url: "https://docs.tech.eus/"
        target: "_blank"

docker:
  version: "3"
  networks:
    nextcloud:
      driver: bridge
      internal: true
    rei3-1:
    rei3-2:
  services:
    homeassistant:
      container_name: homeassistant
      image: "ghcr.io/home-assistant/home-assistant:stable"
      volumes:
        - /mnt/storage/AppData/homeassistant/config:/config
        - /mnt/storage/Media:/media
        - /etc/localtime:/etc/localtime:ro
      restart: unless-stopped
      privileged: true
      network_mode: host
    homer:
      image: b4bz/homer
      container_name: homer
      volumes:
        - /mnt/storage/AppData/homer:/www/assets
      ports:
        - 8080:8080
      user: 1000:1000
      environment:
        - INIT_ASSETS=1
    nextcloud:
      image: nextcloud
      container_name: nextcloud
      ports:
        - "8082:80"
      volumes:
        - /mnt/storage/AppData/nextcloud/html:/var/www/html
      restart: unless-stopped
      depends_on:
        - nextcloud_db
      links:
        - nextcloud_db
      networks:
        - default
        - nextcloud
      environment:
        - MYSQL_HOST=nextcloud_db
        - MYSQL_PASSWORD=dwelled-sacred-reason-amperage
        - MYSQL_DATABASE=nextcloud
        - MYSQL_USER=nextcloud
        - TRUSTED_PROXIES=0.0.0.0/0
        - OVERWRITEPROTOCOL=https
        - OVERWRITEHOST=nextcloud.ei.tech.eus
      logging:
        options:
          max-size: "5m"
          max-file: "3"

    nextcloud_db:
      image: yobasystems/alpine-mariadb:10.11.5
      container_name: nextcloud_db
      volumes:
        - /mnt/storage/AppData/nextcloud/db:/var/lib/mysql
      environment:
        - MYSQL_ROOT_PASSWORD=dwelled-sacred-reason-amperage
        - MYSQL_DATABASE=nextcloud
        - MYSQL_USER=nextcloud
        - MYSQL_PASSWORD=dwelled-sacred-reason-amperage
      restart: unless-stopped
      networks:
        - nextcloud
      logging:
        options:
          max-size: "5m"
          max-file: "3"
    pihole:
      container_name: pihole
      image: pihole/pihole:latest
      hostname: HomePi
      restart: unless-stopped
      ports:
        - "53:53/tcp"
        - "53:53/udp"
        - "67:67/udp"
        - "8081:80/tcp"
      environment:
        TZ: "Europe/Madrid"
        WEBPASSWORD: "capture-clutter-bulginess-suds"
        # ServerIP: REPLACEME
        # ServerIPv6: REPLACEME
        # IPv6: 'true'
      volumes:
        - /mnt/storage/AppData/pihole/etc-pihole/:/etc/pihole/
        - /mnt/storage/AppData/pihole/etc-dnsmasq.d/:/etc/dnsmasq.d/
      dns:
        - 127.0.0.1
        - 1.1.1.1
      # Recommended but not required (DHCP needs NET_ADMIN)
      #   https://github.com/pi-hole/docker-pi-hole#note-on-capabilities
      cap_add:
        - NET_ADMIN
      logging:
        options:
          max-size: "5m"
          max-file: "3"
    axelaula-getaldea:
      image: ghcr.io/sistemaaxel/axelaula:main
      ports:
        - "12321:12321"
      restart: always
      volumes:
        - /mnt/storage/AppData/axelaula/global:/usr/src/app/data
      dns:
        - 8.8.4.4
      environment:
        - "ET_USER=getaldea"
        - "ET_PASS=unfixed-smartness-purse-vividness"

    axelaula-translator:
      image: ghcr.io/sistemaaxel/axelaula:main
      ports:
        - "12320:12321"
      command: python3 translator.py
      restart: always
      environment:
        - "ET_USER=public_axau"
        - "ET_PASS=unfixed-smartness-purse-vividness"
      #  - /mnt/storage/AppData/axelaula/global:/usr/src/app/data
      dns:
        - 8.8.4.4
    paperless_broker:
      image: redis:7.2
      container_name: paperless_broker
      restart: unless-stopped

    paperless_db:
      image: postgres:16
      container_name: paperless_db
      restart: unless-stopped
      volumes:
        - /mnt/storage/AppData/paperlessngx/db/pgdata:/var/lib/postgresql/data
      environment:
        POSTGRES_DB: paperless
        POSTGRES_USER: paperless
        POSTGRES_PASSWORD: paperless

    paperless_web:
      image: ghcr.io/paperless-ngx/paperless-ngx:latest
      container_name: paperless_web
      restart: unless-stopped
      depends_on:
        - paperless_db
        - paperless_broker
      ports:
        - 2226:8000
      healthcheck:
        test: ["CMD", "curl", "-f", "http://localhost:8000"]
        interval: 30s
        timeout: 10s
        retries: 5
      volumes:
        - /mnt/storage/AppData/paperlessngx/data:/usr/src/paperless/data
        - /mnt/storage/AppData/paperlessngx/media:/usr/src/paperless/media
        - /mnt/storage/AppData/paperlessngx/export:/usr/src/paperless/export
        - /mnt/storage/AppData/paperlessngx/consume:/usr/src/paperless/consume
      environment:
        PAPERLESS_REDIS: redis://paperless_broker:6379
        PAPERLESS_DBHOST: paperless_db
        USERMAP_UID: 1000
        USERMAP_GID: 1000
        PAPERLESS_OCR_LANGUAGE: eng+esp+eus
        PAPERLESS_TIME_ZONE: Europe/Madrid
        # PAPERLESS_SECRET_KEY: SuperS4FE!123456
        # PAPERLESS_ADMIN_USER: bitteaendern
        # PAPERLESS_ADMIN_PASSWORD: p4sswort
    motioneye:
      container_name: motioneye
      ports:
          - 8765:8765
          - 7700:7700
          - 7701:7701
          - 7702:7702
          - 7703:7703
          - 7704:7704
          - 7705:7705
      hostname: motioneye
      volumes:
          - /etc/localtime:/etc/localtime:ro
          - /mnt/storage/AppData/MotionEye/etc/motioneye:/etc/motioneye
          - /mnt/storage/AppData/MotionEye/var/lib/motioneye:/var/lib/motioneye
      restart: always
      image: ccrisan/motioneye:master-amd64

    ersatztv:
      container_name: ersatztv
      environment:
        - TZ=Europe/Madrid
      ports:
        - 8409:8409
      volumes:
        - /home/naiel/ersatztv/config:/root/.local/share/ersatztv
        - /mnt/storage/Media:/margaretmedia:ro
      restart: unless-stopped
      image: jasongdove/ersatztv

    kdenlive:
      image: lscr.io/linuxserver/kdenlive:latest
      security_opt:
        - seccomp:unconfined #optional
      environment:
        - PUID=1000
        - PGID=1000
        - TZ=Europe/Madrid
        - SUBFOLDER=/ #optional
      volumes:
        - /mnt/storage/AppData/kdenlive/config:/config
        - /mnt/storage:/margaretstorage
      ports:
        - 3031:3001
      devices:
        - /dev/dri:/dev/dri #optional
      shm_size: "6gb" #optional
      restart: unless-stopped
    filebrowser:
      volumes:
            - /mnt/storage:/mnt/storage
            - /mnt/storage/AppData/filebrowser/filebrowser.db:/database/filebrowser.db
            - /mnt/storage/AppData/filebrowser/settings.json:/config/settings.json
      environment:
            - PUID=1000
            - PGID=1000
      ports:
            - 8809:80
      image: filebrowser/filebrowser:s6

    d01_db:
        environment:
            POSTGRES_PASSWORD: app
            POSTGRES_USER: app
        image: postgres:latest
        restart: always
        volumes:
            - /mnt/storage/AppData/d01/data_db:/var/lib/postgresql/data
    d01:
        build:
            context: https://github.com/r3-team/r3_docker.git#main
            args:
                r3_db_host: r3_db
                r3_os_arch: x64
                r3_version: 3.6.1
                im_policy: /etc/ImageMagick-6/policy.xml
        image: "rei3-d01"
        links:
            - d01_db:r3_db
        ports:
            - "14000:80"
        restart: always
        volumes:
            - /mnt/storage/AppData/d01/data_app:/opt/r3/data
    d02_db:
        environment:
            POSTGRES_PASSWORD: app
            POSTGRES_USER: app
        image: postgres:latest
        restart: always
        volumes:
            - /mnt/storage/AppData/d02/data_db:/var/lib/postgresql/data
    d02:
        build:
            context: https://github.com/r3-team/r3_docker.git#main
            args:
                r3_db_host: r3_db
                r3_os_arch: x64
                r3_version: 3.6.1
                im_policy: /etc/ImageMagick-6/policy.xml
        image: "rei3-d02"
        links:
            - d02_db:r3_db
        ports:
            - "14001:80"
        restart: always
        volumes:
            - /mnt/storage/AppData/d02/data_app:/opt/r3/data
    wyoming-whisper:
        ports:
            - 10300:10300
        volumes:
            - /mnt/storage/AppData/assist/whisper/data:/data
        image: rhasspy/wyoming-whisper
        command: --model tiny-int8 --language es
    wyoming-piper:
        ports:
            - 10200:10200
        volumes:
            - /mnt/storage/AppData/assist/piper/data:/data
        image: rhasspy/wyoming-piper
        command: --voice es_ES-sharvard-medium
    wyoming-openwakeword:
        ports:
            - 10400:10400
        image: rhasspy/wyoming-openwakeword
        command: --preload-model 'alexa'

        
    euskaditech:
        ports:
            - 15000:15000
        volumes:
            - /data:/mnt/storage/AppData/EuskadiTech/Aula2.0/server
        restart: always
        environment:
            - ET_SECRET_KEY=barrette premium paralyze subsystem punch
            - ET_MAIL_PASSWORD=Rubiales26#Ab
        image: ghcr.io/euskaditech/euskaditech:aula-2.0-server
