homelab:
  name: Homelab
  subtitle: EuskadiTech
  icon: "fas fa-home"

warning:
  enabled: true
  title: "Conectividad Limitada"
  content: "El router Vodafone no esta completamente operativo, Algunos dispositivos no tendran internet."

reverse_proxy:
  - domain_name: hl.tech.eus
    scheme: http
    host: 100.70.86.61 # Margaret Tailscale
    port: 8080
  - domain_name: tech.eus
    scheme: http
    host: 100.70.86.61 # Margaret Tailscale
    port: 8080
  - domain_name: ffplayout.ei.tech.eus
    scheme: http
    host: 100.70.86.61 # Margaret Tailscale
    port: 8787
  - domain_name: homeassistant.ei.tech.eus
    scheme: http
    host: 100.70.86.61 # Margaret Tailscale
    port: 8123
  - domain_name: cups.ei.tech.eus
    scheme: http
    host: 100.70.86.61 # Margaret Tailscale
    port: 631
  - domain_name: pihole.ei.tech.eus
    scheme: http
    host: 100.70.86.61 # Margaret Tailscale
    port: 8081
  - domain_name: getaldea.axau.tech.eus
    scheme: http
    host: 100.70.86.61 # Margaret Tailscale
    port: 12321
  - domain_name: translator.axau.tech.eus
    scheme: http
    host: 100.70.86.61 # Margaret Tailscale
    port: 12320


  - domain_name: ba.tech.eus
    scheme: http
    host: 100.90.166.97 # Work01 Tailscale
    port: 14000
  - domain_name: bb.tech.eus
    scheme: http
    host: 100.90.166.97 # Work01 Tailscale
    port: 14001


  - domain_name: docs.tech.eus
    scheme: http
    host: 100.115.231.1 # Huevo23 Tailscale
    port: 82
  - domain_name: nodered.ei.tech.eus
    scheme: http
    host: 100.115.231.1 # Huevo23 Tailscale
    port: 1880

  - domain_name: nginxproxymanager.ei.tech.eus
    scheme: http
    host: 127.0.0.1 # Localhost (Nginx Proxy Manager)
    port: 81

dashboard:
  - name: "Automatización"
    icon: "fas fa-home"
    items:
      - name: "Home Assistant"
        url: "https://homeassistant.ei.tech.eus/"
        target: "_blank"
      - name: "Node-RED (Dashboard)"
        url: "https://nodered.ei.tech.eus/dashboard/tablet-cocina"
        target: "_blank"
  - name: "Datos"
    icon: "fas fa-home"
    items:
      - name: "Nextcloud"
        url: "https://nextcloud.ei.tech.eus/"
        target: "_blank"
      - name: "Rei3 Alpha"
        url: "https://ba.tech.eus/"
      - name: "Rei3 Beta"
        url: "https://bb.tech.eus/"
        target: "_blank"
  - name: "Red"
    icon: "fas fa-wifi"
    items:
      - name: "Nginx Proxy Manager"
        url: "https://nginxproxymanager.ei.tech.eus/"
        target: "_blank"
      - name: "Pi-Hole"
        url: "https://pihole.ei.tech.eus/"
        target: "_blank"
      - name: "Router Vodafone"
        url: "http://192.168.0.1"
        target: "_blank"
      - name: "Repetidor TP-Link"
        url: "http://192.168.0.2"
        target: "_blank"
  - name: "Infraestructura"
    icon: "fas fa-server"
    items:
      - name: "Homelab Repo"
        url: "https://github.com/naielv/homelab"
        target: "_blank"
      - name: "Impresoras"
        url: "https://cups.ei.tech.eus/"
        target: "_blank"
      - name: "Generar Contraseña"
        url: "https://www.useapassphrase.com/"
        target: "_blank"
      - name: "Cloudflare"
        url: "https://dash.cloudflare.com/"
        target: "_blank"
      - name: "Documentación"
        url: "https://docs.tech.eus/"
        target: "_blank"


docker:
  version: '3'
  networks:
    nextcloud:
      driver: bridge
      internal: true
  services:
    homeassistant:
      container_name: homeassistant
      image: "ghcr.io/home-assistant/home-assistant:stable"
      volumes:
        - /mnt/storage/AppData/homeassistant/config:/config
        - /mnt/storage/Media:/media
        - /etc/localtime:/etc/localtime:ro
      restart: unless-stopped
      privileged: true
      network_mode: host
    homer:
      image: b4bz/homer
      container_name: homer
      volumes:
        - /mnt/storage/AppData/homer:/www/assets
      ports:
        - 8080:8080
      user: 1000:1000
      environment:
        - INIT_ASSETS=1
    nextcloud:
      image: nextcloud
      container_name: nextcloud
      ports:
        - "8082:80"
      volumes:
        - /mnt/storage/AppData/nextcloud/html:/var/www/html
      restart: unless-stopped
      depends_on: 
        - nextcloud_db
      links:
        - nextcloud_db
      networks:
        - default
        - nextcloud
      environment:
        - MYSQL_HOST=nextcloud_db
        - MYSQL_PASSWORD=dwelled-sacred-reason-amperage
        - MYSQL_DATABASE=nextcloud
        - MYSQL_USER=nextcloud
        - TRUSTED_PROXIES=0.0.0.0/0
        - OVERWRITEPROTOCOL=https
        - OVERWRITEHOST=nextcloud.ei.tech.eus
      logging:
        options:
          max-size: "5m"
          max-file: "3"

    nextcloud_db:
      image: yobasystems/alpine-mariadb:10.11.5
      container_name: nextcloud_db
      volumes:
        - /mnt/storage/AppData/nextcloud/db:/var/lib/mysql
      environment:
        - MYSQL_ROOT_PASSWORD=dwelled-sacred-reason-amperage
        - MYSQL_DATABASE=nextcloud
        - MYSQL_USER=nextcloud
        - MYSQL_PASSWORD=dwelled-sacred-reason-amperage
      restart: unless-stopped
      networks:
        - nextcloud
      logging:
        options:
          max-size: "5m"
          max-file: "3"
    pihole:
      container_name: pihole
      image: pihole/pihole:latest
      hostname: HomePi
      restart: unless-stopped
      ports:
        - "53:53/tcp"
        - "53:53/udp"
        - "67:67/udp"
        - "8081:80/tcp"
      environment:
        TZ: 'Europe/Madrid'
        WEBPASSWORD: 'capture-clutter-bulginess-suds'
        # ServerIP: REPLACEME
        # ServerIPv6: REPLACEME
        # IPv6: 'true'
      volumes:
        - /mnt/storage/AppData/pihole/etc-pihole/:/etc/pihole/
        - /mnt/storage/AppData/pihole/etc-dnsmasq.d/:/etc/dnsmasq.d/
      dns:
        - 127.0.0.1
        - 1.1.1.1
      # Recommended but not required (DHCP needs NET_ADMIN)
      #   https://github.com/pi-hole/docker-pi-hole#note-on-capabilities
      cap_add:
        - NET_ADMIN
      logging:
        options:
          max-size: "5m"
          max-file: "3"
    axelaula-getaldea:
      image: ghcr.io/sistemaaxel/axelaula:main
      ports:
        - "12321:12321"
      restart: always
      volumes:
        - /mnt/storage/AppData/axelaula/getaldea:/usr/src/app/data
        
    axelaula-translator:
      image: ghcr.io/sistemaaxel/axelaula:main
      ports:
        - "12320:12321"
      command: python3 translator.py
      restart: always
      environment:
        - 'ET_USER=public_axau'
        - 'ET_PASS=unfixed-smartness-purse-vividness'
      #  - /mnt/storage/AppData/axelaula/getaldea:/usr/src/app/data
    paperless_broker:
      image: redis:7.2
      container_name: paperless_broker
      restart: unless-stopped

    paperless_db:
      image: postgres:16
      container_name: paperless_db
      restart: unless-stopped
      volumes:
        - /mnt/storage/AppData/paperlessngx/db/pgdata:/var/lib/postgresql/data
      environment:
        POSTGRES_DB: paperless
        POSTGRES_USER: paperless
        POSTGRES_PASSWORD: paperless

    paperless_web:
      image: ghcr.io/paperless-ngx/paperless-ngx:latest
      container_name: paperless_web
      restart: unless-stopped
      depends_on:
        - paperless_db
        - paperless_broker
      ports:
        - 2226:8000
      healthcheck:
        test: ["CMD", "curl", "-f", "http://localhost:8000"]
        interval: 30s
        timeout: 10s
        retries: 5
      volumes:
        - /mnt/storage/AppData/paperlessngx/data:/usr/src/paperless/data
        - /mnt/storage/AppData/paperlessngx/media:/usr/src/paperless/media
        - /mnt/storage/AppData/paperlessngx/export:/usr/src/paperless/export
        - /mnt/storage/AppData/paperlessngx/consume:/usr/src/paperless/consume
      environment:
        PAPERLESS_REDIS: redis://paperless_broker:6379
        PAPERLESS_DBHOST: paperless_db
        USERMAP_UID: 1000
        USERMAP_GID: 1000
        PAPERLESS_OCR_LANGUAGE: eng+esp+eus
        PAPERLESS_TIME_ZONE: Europe/Madrid
        # PAPERLESS_SECRET_KEY: SuperS4FE!123456
        # PAPERLESS_ADMIN_USER: bitteaendern
        # PAPERLESS_ADMIN_PASSWORD: p4sswort
