version: '3'
services:
  os:
    image: ghcr.io/naielv/axelos:main
    ports:
      - 8099:80
  nginxproxymanager:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    volumes:
      - /srv/local/appdata/nginxproxymanager/nginx_proxy_manager/data:/data
      - /srv/local/appdata/nginxproxymanager/nginx_proxy_manager/letsencrypt:/etc/letsencrypt
