  blocky: 
    image: spx01/blocky
    container_name: blocky
    restart: unless-stopped
    # Optional the instance hostname for logging purpose
    hostname: blocky.freitag
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "2229:4000/tcp"
    environment:
      - TZ=Europe/Berlin # Optional to synchronize the log timestamp with host
    volumes:
      # Optional to synchronize the log timestamp with host
      - /etc/localtime:/etc/localtime:ro
      # config file
      - ./volumes/blocky/logs:/logs
      - ./volumes/blocky/config.yml:/app/config.yml # create this! read the docs @ https://github.com/0xERR0R/blocky