  freepbx-app:
    image: epandi/asterisk-freepbx-arm:17.15-latest
    container_name: freepbx-app
    restart: unless-stopped
    ports:
      #### If you aren't using a reverse proxy
      - 2233:80
      - 5060:5060/udp
      - 5160:5160/udp
      - 18000-18100:18000-18100/udp
      #### Flash Operator Panel
      - 4445:4445
    volumes:
      - ./volumes/asterisk17/certs:/certs
      - ./volumes/asterisk17/data:/data
      - ./volumes/asterisk17/logs:/var/log
      - ./volumes/asterisk17/data/www:/var/www/html
      ### Only Enable this option below if you set DB_EMBEDDED=TRUE
      - ./volumes/asterisk17/db:/var/lib/mysql
    environment:
      - VIRTUAL_HOST=asterisk.local
      - VIRTUAL_NETWORK=nginx-proxy
      ### If you want to connect to the SSL Enabled Container
      #- VIRTUAL_PORT=443
      #- VIRTUAL_PROTO=https
      - VIRTUAL_PORT=80
      # - LETSENCRYPT_HOST=hostname.example.com
      # - LETSENCRYPT_EMAIL=email@example.com
      # - DEBUG_MODE=TRUE
      - ZABBIX_HOSTNAME=freepbx-app
      - RTP_START=18000
      - RTP_FINISH=18100
      ## Use for External MySQL Server
      - DB_EMBEDDED=TRUE
      ### These are only necessary if DB_EMBEDDED=FALSE
      # - DB_HOST=freepbx-db
      # - DB_PORT=3306
      # - DB_NAME=asterisk
      # - DB_USER=asterisk
      # - DB_PASS=asteriskpass
      ### If you are using TLS Support for Apache to listen on 443 in the container drop them in /certs and set these:
      #- TLS_CERT=cert.pem
      #- TLS_KEY=key.pem
    ### These final lines are for Fail2ban. If you don't want, comment and also add ENABLE_FAIL2BAN=FALSE to your environment
    cap_add:
      - NET_ADMIN
    # Get privilege from Host (not recommended)
    # privileged: true