  influxdb:
    container_name: influxdb
    image: influxdb:1.8 # caution, this is deprecated
    restart: unless-stopped
    ports:
    - "8086:8086"
    - "8083:8083"
    - "2003:2003"
    environment:
    - "INFLUXDB_DB=MAIN"
    # - "INFLUXDB_DATA_ENGINE=tsm1"
    - "INFLUXDB_REPORTING_DISABLED=false"
    - "INFLUXDB_STORE_ENABLED=false"
    - "INFLUXDB_QUERY_LOG_ENABLED=false"
    - "INFLUXDB_ADMIN_ENABLED=true"
      # -  "INFLUXDB_HTTP_AUTH_ENABLED=true"
      # -  "INFLUXDB_ADMIN_USER=admin"
      # -  "INFLUXDB_ADMIN_PASSWORD=password_placeholder"
    - "INFLUXDB_USER=admin"
    - "INFLUXDB_USER_PASSWORD=raspberry"
      # -  "INFLUXDB_READ_USER=readuser"
      # -  "INFLUXDB_READ_USER_PASSWORD=password_placeholder"
      # -  "INFLUXDB_WRITE_USER=writeuser"
      # -  "INFLUXDB_WRITE_USER_PASSWORD=password_placeholder"
    # # Enable Traefik Log
    # - "INFLUXDB_UDP_ENABLED=true"
    # - "INFLUXDB_UDP_BIND_ADDRESS=0.0.0.0:8089"
    # - "INFLUXDB_UDP_DATABASE=traefik"
    volumes:
    - ./volumes/influxdb/data:/var/lib/influxdb
    - ./backups/influxdb/db:/var/lib/influxdb/backup
    logging:
      options:
        max-size: "5m"
        max-file: "3"