  iobroker:
    restart: unless-stopped
    image: buanet/iobroker:latest
    container_name: iobroker
    hostname: iobroker
    ports:
      - "8081:8081"
    volumes:
      - ./volumes/iobroker:/opt/iobroker