  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    user: 0:0 # UserID:GroupID
    network_mode: 'host'
    volumes:
      - ./volumes/jellyfin/config:/config
      - ./volumes/jellyfin/cache:/cache
      - ./volumes/jellyfin/media:/media
      # - ./volumes/immich/fotos/library:/photos:ro
    restart: 'unless-stopped'
    # Optional - alternative address used for autodiscovery
    # environment:
    #   - JELLYFIN_PublishedServerUrl=http://example.com