  openhab:
    container_name: openhab
    image: "openhab/openhab:latest"
    restart: always
    network_mode: host
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - ./volumes/openhab/openhab_addons:/openhab/addons
      - ./volumes/openhab/openhab_conf:/openhab/conf
      - ./volumes/openhab/openhab_userdata:/openhab/userdata
    environment:
      - OPENHAB_HTTP_PORT=8082
      - OPENHAB_HTTPS_PORT=8443"
      - EXTRA_JAVA_OPTS=-Duser.timezone=Europe/Berlin"