  timescaledb:
    container_name: timescaledb
    image: timescale/timescaledb:latest-pg12
    restart: unless-stopped
    environment:
      - POSTGRES_USER=timescaleuser
      - POSTGRES_PASSWORD=password_placeholder
      - POSTGRES_DB=postdb
    ports:
      - "5432:5432"
    volumes:
      - ./volumes/timescaledb/data:/var/lib/postgresql/data