  wyoming-piper:
    container_name: wyoming-piper
    image: rhasspy/wyoming-piper # https://github.com/home-assistant/addons/blob/master/piper/DOCS.md
    command: --voice de-thorsten-low --length-scale 1.0
    volumes:
      - ./volumes/wyoming/piper:/data
    environment:
      - TZ=Europe/Berlin
    restart: unless-stopped
    ports:
      - 10200:10200