version: '3'
services:
  odoo:
    image: odoo:17.0
    deploy:
      labels:
        - traefik.enable=true
        - traefik.docker.network=proxy
        - traefik.http.routers.odoo-http.rule=Host(`tech.eus`)
        - traefik.http.routers.odoo-http.entrypoints=http
        - traefik.http.routers.odoo-http.middlewares=https-redirect
        - traefik.http.routers.odoo-https.rule=Host(`tech.eus`)
        - traefik.http.routers.odoo-https.entrypoints=https
        - traefik.http.routers.odoo-https.tls=true
        #- traefik.http.routers.odoo-https.tls.certresolver=le
        - traefik.http.services.odoo.loadbalancer.server.port=8069
    networks:
      proxy:
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=a_strong_password_for_user
      - POSTGRES_USER=odoo
      - PGDATA=/var/lib/postgresql/data/pgdata
      - HOST=postgres
      - USER=odoo
      - PASSWORD=a_strong_password_for_user
    depends_on:
      - postgres
    ports:
      - "8069:8069"
    volumes:
      - /glusterstor/Homelab/odoo/data:/var/lib/odoo
  postgres:
    image: postgres:13
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=a_strong_password_for_user
      - POSTGRES_USER=odoo
      - PGDATA=/var/lib/postgresql/data/pgdata
      - HOST=postgres
      - USER=odoo
      - PASSWORD=a_strong_password_for_user

    volumes:
      - /glusterstor/Homelab/odoo/db:/var/lib/postgresql/data/pgdata

networks:
  proxy:
    external: True