version: '3'
services:
  nginxproxymanager:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    volumes:
      - /glusterstor/Homelab/nginxproxymanager/nginx_proxy_manager/data:/data
      - /glusterstor/Homelab/nginxproxymanager/nginx_proxy_manager/letsencrypt:/etc/letsencrypt
