---
title: "Homelab"
subtitle: "EuskadiTech"
documentTitle: "Homelab"
icon: "fas fa-home"
header: true
footer: false
columns: 4
connectivityCheck: true
defaults:
  layout: columns
  colorTheme: auto
theme: default
message:
#  url: https://api.chucknorris.io/jokes/random
#  mapping:
#    title: 'id'
#    content: 'value'
#  refreshInterval: 10000
  style: "is-warning"
  title: "Conectividad Limitada"
  icon: "fa fa-exclamation-triangle"
  content: "El router Vodafone no esta completamente operativo, Algunos dispositivos no tendran internet."
links: []
services:
  - name: "Automatización"
    icon: "fas fa-home"
    items:
      - name: "Home Assistant"
        url: "https://homeassistant.ei.tech.eus/"
        target: "_blank"
      - name: "Node-RED (Dashboard)"
        url: "https://nodered.ei.tech.eus/dashboard/tablet-cocina"
        target: "_blank"
  - name: "Datos"
    icon: "fas fa-home"
    items:
      - name: "Nextcloud"
        url: "https://nextcloud.ei.tech.eus/"
        target: "_blank"
      - name: "Rei3 Alpha"
        url: "https://ba.tech.eus/"
      - name: "Rei3 Beta"
        url: "https://bb.tech.eus/"
        target: "_blank"
  - name: "Red"
    icon: "fas fa-wifi"
    items:
      - name: "Nginx Proxy Manager"
        url: "https://nginxproxymanager.ei.tech.eus/"
        target: "_blank"
      - name: "Pi-Hole"
        url: "https://pihole.ei.tech.eus/"
        target: "_blank"
      - name: "Router Vodafone"
        url: "http://192.168.0.1"
        target: "_blank"
      - name: "Repetidor TP-Link"
        url: "http://192.168.0.2"
        target: "_blank"
  - name: "Infraestructura"
    icon: "fas fa-server"
    items:
      - name: "Homelab Repo"
        url: "https://github.com/naielv/homelab"
        target: "_blank"
      - name: "Impresoras"
        url: "https://cups.ei.tech.eus/"
        target: "_blank"
      - name: "Generar Contraseña"
        url: "https://www.useapassphrase.com/"
        target: "_blank"
      - name: "Cloudflare"
        url: "https://dash.cloudflare.com/"
        target: "_blank"
