name: Docker dry-run

on:
  workflow_dispatch:
  pull_request:
    paths:
        - 'docker/**'

jobs:
  deploy:
    runs-on: "self-hosted"
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Upload new Config Files
        uses: appleboy/scp-action@master
        with:
          username: naiel
          host: margaret2.ip.tech.eus
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: './docker/*'
          target: '~/naiel-docker-dry-run'
          overwrite: true
          strip_components: 1
      - name: Restart Docker Containers (DRY RUN) @ Margaret
        uses: fifsky/ssh-action@master
        with:
          user: naiel
          host: margaret2.ip.tech.eus # Reserved IP Address (to my local device) (example 192.168.0.1)
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          command: |
            cd ~/naiel-docker-dry-run
            docker compose --dry-run up -d
