name: Update Docs

on:
  push:
    branches: ["main"]
    paths:
      - 'docs/**'
  workflow_dispatch:
jobs:
  deploy:
    runs-on: "self-hosted"
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Delete old docs @ Huevo23
        uses: fifsky/ssh-action@master
        with:
          user: pi
          host: huevo23.ip.tech.eus # Reserved IP Address (to my local device) (example 192.168.0.1)
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          command: sudo rm ~/ei23-docker/volumes/ei23/docs/* -r ; chmod -R 777 ~/ei23-docker/volumes/ei23/docs
      - name: Upload new Files
        uses: appleboy/scp-action@master
        with:
          username: pi
          host: huevo23.ip.tech.eus
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: './docs/*'
          target: '~/ei23-docker/volumes/ei23/docs'
          overwrite: true
          strip_components: 1
      - name: Build Docs @ Huevo23
        uses: fifsky/ssh-action@master
        with:
          user: pi
          host: huevo23.ip.tech.eus # Reserved IP Address (to my local device) (example 192.168.0.1)
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          command: bash ~/ei23.sh docs && sudo chmod -R 777 ei23-docker/volumes/ei23/docs/site/