name: Update Homer Config

on:
  push:
    branches: ["main"]
    paths:
      - 'config.yml'
      - 'tools/homer.py'
  workflow_dispatch:

jobs:
  build:
    runs-on: "ubuntu-latest"
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.x"
      - name: Install pyyaml
        run: pip install pyyaml
          
      - name: Run Build Tool
        run: |
          cd tools
          python3 homer.py
      - name: "Upload build artifacts"
        uses: actions/upload-artifact@v4
        with:
          name: homer_build
          path: build/homer.yml
    
    
  deploy:
    name: Deploy homer config
    needs:
      - build
    runs-on: "self-hosted"
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: "Download build artifacts"
        uses: actions/download-artifact@v4
        with:
          name: homer_build
          path: build/homer.yml
      - name: Set permissions @ Margaret
        uses: fifsky/ssh-action@master
        with:
          user: naiel
          host: margaret2.ip.tech.eus # Reserved IP Address (to my local device) (example 192.168.0.1)
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          command: sudo chmod -R 777 /mnt/storage/AppData/homer

      - name: Upload new Config Files
        uses: appleboy/scp-action@master
        with:
          username: naiel
          host: margaret2.ip.tech.eus
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: './build'
          target: '/mnt/storage/AppData/homer/'
          overwrite: true
          strip_components: 3
      - name: Restart Homer Container @ Margaret
        uses: fifsky/ssh-action@master
        with:
          user: naiel
          host: margaret2.ip.tech.eus # Reserved IP Address (to my local device) (example 192.168.0.1)
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          command: |
            cd ~/naiel-docker
            docker compose restart homer
  cleanup:
    name: Cleanup actions
    needs:
      - deploy
    runs-on: ubuntu-latest
    steps:
      - name: "Remove build artifacts"
        uses: geekyeggo/delete-artifact@v1
        with:
          name: homer_build