name: Update Homer Config

on:
  push:
    paths:
      - 'homer/**'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: "self-hosted"
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Upload new Config Files
        uses: appleboy/scp-action@master
        with:
          username: naiel
          host: margaret2.ip.tech.eus
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: './homer/*'
          target: '/mnt/storage/AppData/homer'
          overwrite: true
          strip_components: 1
