name: Update Config Files

on:
  push:
    paths:
      - 'homer/**'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: "self-hosted"
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Upload new Config Files
        uses: appleboy/scp-action@master
        with:
          username: root
          host: zimaos.ip.tech.eus
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: './homer/*'
          target: '/var/lib/casaos_data/AppData2/big-bear-homer/assets/'
          overwrite: true
          strip_components: 1
          tar_tmp_path: /var/lib/casaos_data/tmp