# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Tareas Semanales

on:
  workflow_dispatch:
  schedule:
  - cron: '14 3 * * 6'

jobs:
  accounts:
    name: Configurar las cuentas
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v4 
    - name: Action SSH
      id: action-ssh
      uses: tiyee/action-ssh@release
      with:
        host: dietpi
        port: 22
        username: root
        privateKey: ${{ secrets.PRIVATE_KEY }} 
        command: 'cd ~/homelab && git pull && python3 tasks/accounts.py'
  backup:
    name: Iniciar las copias de seguridad
    runs-on: self-hosted
    needs: accounts
    steps:
    - uses: actions/checkout@v4 
    - name: Action SSH
      id: action-ssh
      uses: tiyee/action-ssh@release
      with:
        host: dietpi
        port: 22
        username: root
        privateKey: ${{ secrets.PRIVATE_KEY }} 
        command: 'cd ~/homelab && git pull && screen -dmS weekly_backup python3 tasks/backup.py'
